Added a proper readme in markdown, updated metadata at the top of the script, improved error handling, added a block to standardize S01E01 style info, improved bash and added a few new groups and info tags

diff --git a/download-debrand b/download-debrand
--- a/download-debrand
+++ b/download-debrand
@@ -1,35 +1,30 @@
 #! /usr/bin/env bash
 
-# --------------------------------------------------- #
-#                  download-debrand                   #
-# --------------------------------------------------- #
-# download-debrand is a simple script for removing    #
-# branding and other unwanted information from        #
-# downloaded videos, using http://rename.berlios.de/  #
-#                                                     #
-# Developer: Prurigro                                 #
-# Contact: prurigro at gmail dot com                  #
-# Version: 2.0                                        #
-#                                                     #
-# If you find this script useful but have ideas about #
-# how to make it better, found bugs, need help using  #
-# it or anything else; feel free to contect me.       #
-#                                                     #
-# Distributed under the GPLv3; copies can be obtained #
-# on gnu.org @ http://www.gnu.org/copyleft/gpl.html   #
-# --------------------------------------------------- #
+# ---------------------------------------------------------------------------- #
+#                               download-debrand                               #
+# ---------------------------------------------------------------------------- #
+# A script for sanitizing the filenames of downloaded files that were named by #
+# release groups. It removes branding and information tags, as well as         #
+# standardizing the format of the season and episode identifier.               #
+#                                                                              #
+# By: Kevin MacMartin                                                          #
+# Contact: prurigro at gmail dot com                                           #
+#                                                                              #
+# Distributed under the GPLv3                                                  #
+# Copies can be obtained from gnu.org @ http://www.gnu.org/copyleft/gpl.html   #
+# ---------------------------------------------------------------------------- #
 
 #THE NAMES OF VARIOUS RELEASE GROUPS (CASE SENSITIVE)
-SCENE=('2HD' '2hd' 'AFG' 'ANON' 'ASAP' 'asap' 'BAJSKORV' 'BATV' 'BiA' 'BRiTiSH' 'c4tv' 'CaRaT' 'COMPULSiON' 'DIMENSION' 'EVOLVE' 'EXCELLENCE' 'FEVER' 'FoV' 'FQM' 'fqm' 'HerMes' 'IMMERSE' 'KILLERS' 'killers' 'LOL' 'lol' 'Max' 'MiNT' 'NoTV' 'ORENJI' 'Orenji' 'P0W4' 'PDTV' 'pdtv' 'QCF' 'ReEnc' 'REMARKABLE' 'RiVER' 'RM' 'SaMettv' 'SFD' 'TLA' 'TVSR' 'ViP3R' 'VTV' 'WEB DL' 'WS' 'YIFY')
+SCENE=('2HD' '2hd' 'AFG' 'ANON' 'ASAP' 'asap' 'BAJSKORV' 'BATV' 'BiA' 'BRiTiSH' 'BTN' 'c4tv' 'CaRaT' 'COMPULSiON' 'DIMENSION' 'EVOLVE' 'EXCELLENCE' 'FEVER' 'FoV' 'FQM' 'fqm' 'HerMes' 'IMMERSE' 'KILLERS' 'killers' 'LOL' 'lol' 'Max' 'MiNT' 'NoTV' 'ORENJI' 'Orenji' 'P0W4' 'PDTV' 'pdtv' 'QCF' 'rarbg' 'ReEnc' 'REMARKABLE' 'RiVER' 'RM' 'SaMettv' 'SFD' 'TLA' 'TVSR' 'ViP3R' 'VTV' 'WEB DL' 'WS' 'YIFY')
 
 #TAGS USED BY GROUPS TO GIVE INFORMATION ABOUT THE VIDEO (NOT CASE SENSITIVE)
-INFO=('720p' 'aac' 'bluray' 'ffmpeg' 'hdtv' 'proper' 'repack' 'webrip' 'x264' 'xvid')
+INFO=('720p' 'aac2.0' 'aac' 'bluray' 'ffmpeg' 'h.264' 'hdtv' 'proper' 'repack' 'web-dl' 'webrip' 'x264' 'xvid')
 
 function dd_help {
     SCRIPTNAME=$(sed 's/.*\///g' <<< "$0")
-    echo -e "Name\n\t${SCRIPTNAME} - tool for stripping scene and quality tags from downloads"
+    echo -e "Name\n\t${SCRIPTNAME} - tool for stripping scene and quality tags from downloads."
+    echo -e "\nDESCRIPTION\n\tThis script can be used to remove tags containing scene and quality\n\tinformation from downloads, leaving only the show name and standardized\n\tepisode information."
     echo -e "\nSYNOPSIS\n\t${SCRIPTNAME} [option] files"
-    echo -e "\nDESCRIPTION\n\tThis script can be used to remove tags containing scene and quality\n\tinformation from downloads, leaving only the showname and episode details"
     echo -e "\nOPTIONS"
     echo -e "\t${SCRIPTNAME} -t | --test\n\t\tShow the results of the change without changing any files"
     echo -e "\n\t${SCRIPTNAME} -h | --help\n\t\tDisplay this help"
@@ -41,12 +36,12 @@ function dd_help {
 }
 
 function dd_newname {
-    if [ ! "$NEWNAME" == "$1" ]; then NEWNAME="$1"; fi
+    if [ ! "$NEWNAME" = "$1" ]; then NEWNAME="$1"; fi
 }
 
-if [ -z "$1" ]; then echo -e "Error: please supply input\n"; dd_help; exit 1; fi
-if [ "$1" == "-t" -o "$1" == "--test" ]; then if [ -z "$2" ]; then echo -e "Error: please supply input\n"; dd_help; exit 1; else TEST=true; fi; fi
-if [ "$1" == "-h" -o "$1" == "--help" ]; then dd_help; exit 0; fi
+[[ -z $1 ]] && echo -e "Error: please supply input" && exit 1
+if [ "$1" = "-h" -o "$1" = "--help" ]; then dd_help; exit 0; fi
+if [ "$1" = "-t" -o "$1" = "--test" ]; then [[ -z $2 ]] && echo -e "Error: please supply input" && exit 1 || TEST=true; fi
 
 for file in "$@"; do
     #Only run if $file is writable and exists, and it isn't a block, character, directory or symbolic link
@@ -56,18 +51,24 @@ for file in "$@"; do
 
         for group in ${SCENE[@]}; do dd_newname "$(sed 's/'"$group"'//g' <<< $NEWNAME)"; done
         for info in ${INFO[@]}; do dd_newname "$(sed 's/'"$info"'//gi' <<< $NEWNAME)"; done
+
         dd_newname "$(sed 's/\[\]//g' <<< $NEWNAME)" #Remove leftover '[]'s from groups
         dd_newname "$(sed 's/-/\ /g' <<< $NEWNAME)" #Replace '-'s with spaces
         dd_newname "$(sed 's/\./\ /g' <<< $NEWNAME)" #Replace '.'s with spaces
         dd_newname "$(sed 's/\ \ */\ /g' <<< $NEWNAME)" #Replace multiple spaces with a single space
         dd_newname "$(sed 's/\ \([^\ ]*\)$/\.\1/g' <<< $NEWNAME)" #Replace the final space with a '.'
 
-        if [ $TEST ]; then
+        dd_newname "$(sed -re 's/S([0-9])E/S0\1E/gi' <<< $NEWNAME)" #Replace S#E with S0#E
+        dd_newname "$(sed -re 's/S([0-9][0-9])E([0-9][^[0-9])/S\1E0\2/gi' <<< $NEWNAME)" #Replace S##E# with S0#E0#
+        dd_newname "$(sed -re 's/s([0-9]*)e([0-9]*)/S\1E\2/gi' <<< $NEWNAME)" #Replace s##e## with S##E##
+
+        if [[ $TEST ]]; then
             echo -n "TESTING: "
-            if [ ! "$FILENAME" == "$NEWNAME" ]; then echo "$FILENAME -> $NEWNAME"
-            else echo "No change to $FILENAME"; fi
+            if [[ -n $NEWNAME ]]; then [[ ! "$FILENAME" = "$NEWNAME" ]] && echo "${FILENAME} -> ${NEWNAME}" || echo "No change to ${FILENAME}"
+            else echo "Error while debranding ${FILENAME}"; fi
         else
-            if [ ! "$FILENAME" == "$NEWNAME" ]; then mv "$FILENAME" "$NEWNAME"; fi
+            if [[ -n $NEWNAME ]]; then [[ ! "$FILENAME" = "$NEWNAME" ]] && mv "$FILENAME" "$NEWNAME"
+            else echo "Error while debranding ${FILENAME}"; fi
         fi
     fi
 done
